export const userConstants = {
  CU_Req: "CU_Req",
  CUSuc: "CU_SUC",
  CUErr: "CU_ERR",
  URErr: "UR_ERR",
  ULErr: "UL_ERR",
  UProfile: "U_PROFILE",
  UData: "U_DATA",
  UList: "U_LIST",
  UListDel: "U_LIST_DEL",
  UListUpt: "U_LIST_UPT",
  USER_SECURITY_QUESTIONS_REQ: "USER_SECURITY_QUESTIONS_REQ",
  USER_SECURITY_QUESTIONS: "USER_SECURITY_QUESTIONS",
  USER_SECURITY_QUESTION_ERR: "USER_SECURITY_QUESTION_ERR",
  MATCH_SECURITY_ANSWERS_REQ: "MATCH_SECURITY_ANSWERS_REQ",
  MATCH_SECURITY_ANSWERS: "MATCH_SECURITY_ANSWERS",
  MATCH_SECURITY_ANSWERS_ERR: "MATCH_SECURITY_ANSWERS_ERR",
  CAN_RESET_PASSWORD: "CAN_RESET_PASSWORD",
  PASSWORD_CHANGE_REQ: "PASSWORD_CHANGE_REQ",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  PASSWORD_CHANGE_ERR: "PASSWORD_CHANGE_ERR",
  ALL_STUDENTS_REQ: "ALL_STUDENTS_REQ",
  ALL_STUDENTS: "ALL_STUDENTS",
  ALL_STUDENTS_ERR: "ALL_STUDENTS_ERR",
  ALL_TEACHERS_REQ: "ALL_TEACHERS_REQ",
  ALL_TEACHERS: "ALL_TEACHERS",
  ALL_TEACHERS_ERR: "ALL_TEACHERS_ERR",
  ACCOUNT_ENABLE_REQ: "ACCOUNT_ENABLE_REQ",
  ACCOUNT_ENABLE: "ACCOUNT_ENABLE",
  ACCOUNT_ENABLE_ERR: "ACCOUNT_ENABLE_ERR",
  UPDATE_COURSEACCESS_REQ: "UPDATE_COURSEACCESS_REQ",
  UPDATE_COURSEACCESS_ERR: "UPDATE_COURSEACCESS_ERR",
  UPDATE_COURSEACCESS: "UPDATE_COURSEACCESS",
  SEARCH_STUDENTS_REQ: "SEARCH_STUDENTS_REQ",
  SEARCH_STUDENTS_ERR: "SEARCH_STUDENTS_ERR",
  SEARCH_STUDENTS: "SEARCH_STUDENTS",
  ALL_ADMINS: "ALL_ADMINS",
  ALL_ADMINS_REQ: "ALL_ADMINS_REQ",
  ALL_ADMINS_ERR: "ALL_ADMINS_ERR",
  CLEAR_NOTIFICATION_REQ: "CLEAR_NOTIFICATION_REQ",
  CLEAR_NOTIFICATION_ERR: "CLEAR_NOTIFICATION_ERR",
  SELECTED_NOTIFICATION: "SELECTED_NOTIFICATION",

  COMPLETED_LESSONS_REQ: "COMPLETED_LESSONS_REQ",
  COMPLETED_LESSONS_ERR: "COMPLETED_LESSONS_ERR",
  COMPLETED_LESSONS: "COMPLETED_LESSONS",

  ALL_USERS_REQ: "ALL_USERS_REQ",
  ALL_USERS_ERR: "ALL_USERS_ERR",
  ALL_USERS: "ALL_USERS",
  ALL_DOCTORS: "ALL_DOCTORS",
  ALL_NURSES: "ALL_NURSES",
  SELECTED_DOCTOR: "SELECTED_DOCTOR",
};

export const snackBarConstants = {
  ShowSnack: "SHOW_SNACK",
  HideSnack: "HIDE_SNACK",
};

export const provinceConstants = {
  // add
  ADD_PROVINCE_REQ: "ADD_PROVINCE_REQ",
  ADD_PROVINCE_ERR: "ADD_PROVINCE_ERR",
  ADD_PROVINCE: "ADD_PROVINCE",
  // get
  GET_PROVINCE_REQ: "GET_PROVINCE_REQ",
  GET_PROVINCE_ERR: "GET_PROVINCE_ERR",
  GET_PROVINCE: "GET_PROVINCE",
  // update
  UPDATE_PROVINCE_REQ: "UPDATE_PROVINCE_REQ",
  UPDATE_PROVINCE_ERR: "UPDATE_PROVINCE_ERR",
  UPDATE_PROVINCE: "UPDATE_PROVINCE",
  // delete
  DELETE_PROVINCE_REQ: "DELETE_PROVINCE_REQ",
  DELETE_PROVINCE_ERR: "DELETE_PROVINCE_ERR",
  DELETE_PROVINCE: "DELETE_PROVINCE",
};

export const patientConstants = {
  // add
  ADD_PATIENT_REQ: "ADD_PATIENT_REQ",
  ADD_PATIENT_ERR: "ADD_PATIENT_ERR",
  ADD_PATIENT: "ADD_PATIENT",
  PATIENT_ADDED: "PATIENT_ADDED",
  // get
  GET_PATIENT_REQ: "GET_PATIENT_REQ",
  GET_PATIENT_ERR: "GET_PATIENT_ERR",
  GET_PATIENT: "GET_PATIENT",
  // update
  UPDATE_PATIENT_REQ: "UPDATE_PATIENT_REQ",
  UPDATE_PATIENT_ERR: "UPDATE_PATIENT_ERR",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  // delete
  DELETE_PATIENT_REQ: "DELETE_PATIENT_REQ",
  DELETE_PATIENT_ERR: "DELETE_PATIENT_ERR",
  DELETE_PATIENT: "DELETE_PATIENT",
};
export const surgeryConstants = {
  // add
  ADD_SURGERY_REQ: "ADD_SURGERY_REQ",
  ADD_SURGERY_ERR: "ADD_SURGERY_ERR",
  ADD_SURGERY: "ADD_SURGERY",
  SURGERY_ADDED: "SURGERY_ADDED",
  // get
  GET_SURGERY_REQ: "GET_SURGERY_REQ",
  GET_SURGERY_ERR: "GET_SURGERY_ERR",
  GET_SURGERY: "GET_SURGERY",
  // update
  UPDATE_SURGERY_REQ: "UPDATE_SURGERY_REQ",
  UPDATE_SURGERY_ERR: "UPDATE_SURGERY_ERR",
  UPDATE_SURGERY: "UPDATE_SURGERY",
  // delete
  DELETE_SURGERY_REQ: "DELETE_SURGERY_REQ",
  DELETE_SURGERY_ERR: "DELETE_SURGERY_ERR",
  DELETE_SURGERY: "DELETE_SURGERY",
};
export const postSurgeryConstants = {
  // add
  ADD_POST_SURGERY_REQ: "ADD_POST_SURGERY_REQ",
  ADD_POST_SURGERY_ERR: "ADD_POST_SURGERY_ERR",
  ADD_POST_SURGERY: "ADD_POST_SURGERY",
  POST_SURGERY_ADDED: "POST_SURGERY_ADDED",
  // get
  GET_POST_SURGERY_REQ: "GET_POST_SURGERY_REQ",
  GET_POST_SURGERY_ERR: "GET_POST_SURGERY_ERR",
  GET_POST_SURGERY: "GET_POST_SURGERY",
  // update
  UPDATE_POST_SURGERY_REQ: "UPDATE_POST_SURGERY_REQ",
  UPDATE_POST_SURGERY_ERR: "UPDATE_POST_SURGERY_ERR",
  UPDATE_POST_SURGERY: "UPDATE_POST_SURGERY",
  // delete
  DELETE_POST_SURGERY_REQ: "DELETE_POST_SURGERY_REQ",
  DELETE_POST_SURGERY_ERR: "DELETE_POST_SURGERY_ERR",
  DELETE_POST_SURGERY: "DELETE_POST_SURGERY",
};

export const sectorConstants = {
  // add
  ADD_SECTOR_REQ: "ADD_SECTOR_REQ",
  ADD_SECTOR_ERR: "ADD_SECTOR_ERR",
  ADD_SECTOR: "ADD_SECTOR",
  // get
  GET_SECTOR_REQ: "GET_SECTOR_REQ",
  GET_SECTOR_ERR: "GET_SECTOR_ERR",
  GET_SECTOR: "GET_SECTOR",
  // update
  UPDATE_SECTOR_REQ: "UPDATE_SECTOR_REQ",
  UPDATE_SECTOR_ERR: "UPDATE_SECTOR_ERR",
  UPDATE_SECTOR: "UPDATE_SECTOR",
  // delete
  DELETE_SECTOR_REQ: "DELETE_SECTOR_REQ",
  DELETE_SECTOR_ERR: "DELETE_SECTOR_ERR",
  DELETE_SECTOR: "DELETE_SECTOR",
};

export const programtypeConstants = {
  // add
  ADD_PROGRAMTYPE_REQ: "ADD_PROGRAMTYPE_REQ",
  ADD_PROGRAMTYPE_ERR: "ADD_PROGRAMTYPE_ERR",
  ADD_PROGRAMTYPE: "ADD_PROGRAMTYPE",
  // get
  GET_PROGRAMTYPE_REQ: "GET_PROGRAMTYPE_REQ",
  GET_PROGRAMTYPE_ERR: "GET_PROGRAMTYPE_ERR",
  GET_PROGRAMTYPE: "GET_PROGRAMTYPE",
  // update
  UPDATE_PROGRAMTYPE_REQ: "UPDATE_PROGRAMTYPE_REQ",
  UPDATE_PROGRAMTYPE_ERR: "UPDATE_PROGRAMTYPE_ERR",
  UPDATE_PROGRAMTYPE: "UPDATE_PROGRAMTYPE",
  // delete
  DELETE_PROGRAMTYPE_REQ: "DELETE_PROGRAMTYPE_REQ",
  DELETE_PROGRAMTYPE_ERR: "DELETE_PROGRAMTYPE_ERR",
  DELETE_PROGRAMTYPE: "DELETE_PROGRAMTYPE",
};

export const rebateConstants = {
  // add
  ADD_REBATE_REQ: "ADD_REBATE_REQ",
  ADD_REBATE_ERR: "ADD_REBATE_ERR",
  ADD_REBATE: "ADD_REBATE",
  // get
  GET_REBATE_REQ: "GET_REBATE_REQ",
  GET_REBATE_ERR: "GET_REBATE_ERR",
  GET_REBATE: "GET_REBATE",
  // update
  UPDATE_REBATE_REQ: "UPDATE_PROGRAMTYPE_REQ",
  UPDATE_REBATE_ERR: "UPDATE_PROGRAMTYPE_ERR",
  UPDATE_REBATE: "UPDATE_REBATE",
  // delete
  DELETE_REBATE_REQ: "DELETE_REBATE_REQ",
  DELETE_REBATE_ERR: "DELETE_REBATE_ERR",
  DELETE_REBATE: "DELETE_REBATE",
  // search data
  REBATE_SEARCH_DATA_REQ: "REBATE_SEARCH_DATA_REQ",
  REBATE_SEARCH_DATA_ERR: "REBATE_SEARCH_DATA_ERR",
  REBATE_SEARCH_DATA: "REBATE_SEARCH_DATA",
};

export const navBarConstants = { SETCount: "SET_COUNT" };
